version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"

  kafka:
    image:  bitnami/kafka:3.5
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP
    volumes:
      - ./clickhouse-init:/docker-entrypoint-initdb.d

  producer:
    build: ./producer
    depends_on:
      - kafka
